apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec: 
      containers:
      - name: test1
        image: xxxx
        securityContext:
          allowPrivilegeEscalation: false
        lifecycle:
          preStop:
            exec: 
              command: 
              - /bin/sleep
              - "60"
        ports:
        - containerPort: 80
        livenessProbe: 
          httpGet:
            path: /api
            port: 80
          intialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api
            port: 80
          intialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: 300Mi
            cpu: 300m
